### ISSUE TITLE
create JIRA component

### ISSUE THREAD

**Issue by imod** [jenkinsci/bitbucket-approve-plugin#1]
Bugs and feature requests for Jenkins Plugins are tracked in JIRA, please create a JIRA component so we can do the same for this plugin.
Also the link to the Issue Tracker in the Wiki will then start to work (https://wiki.jenkins-ci.org/display/JENKINS/Bitbucket+Approve+Plugin)

**Comment by bhurling** [comment]
Could you point me in the right direction? I tried here: https://issues.jenkins-ci.org/browse/JENKINS#selectedTab=com.atlassian.jira.plugin.system.project%3Acomponents-panel but I can't create components there. Am I missing something?

**Comment by imod** [comment]
no problem...
just ask for it on the mailinglist or IRC (chat) - or you can also tell me your username on the jenkins JIRA and I will create it for you.

**Comment by bhurling** [comment]
That would be great. Its the same username I use on github: bhurling

**Comment by imod** [comment]
done, here it is: https://issues.jenkins-ci.org/browse/JENKINS/component/20024

**Comment by daniel-beck** [comment]
The GH issue tracker should probably be disabled for this repo now.
